# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-27 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set([('email', 'uid')]),
        ),
    ]
