# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-29 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200827_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.CharField(default=uuid.uuid4, max_length=40, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='token',
            unique_together=set([]),
        ),
    ]
