# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-09-11 22:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lists', '0002_auto_20200911_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='shared_with',
        ),
        migrations.AddField(
            model_name='list',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_with', to=settings.AUTH_USER_MODEL),
        ),
    ]
