# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-08-26 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_list_item_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['pk']},
        ),
    ]
